### PR TITLE
Added evaluation with 8 pins

### PR DESCRIPTION
**Pull request by Bukmop123**
beside the i2c it is now possible to get the raw position with the given 8 pins. See example ace128_8Pins_test for more

### CODE REVIEW

**Comment by arielnh56** [comment]
I'm thinking this pull request is broken - not your code, but the pull request only. I suspect if I meerge it it will create a new ACE128 folder under ACE128  i.e. ACE128/ACE128. I've never been on the receiving end of a pull request before so I may be wrong - but this looks like it will duplicate everything. 

I suspect the root of your local git repo is above ACE128 no in ACE128. 

If you can fix that, I'll be able to see the diff and figure out what you did :-)

**Comment by arielnh56** [comment]
that's better :-)

**Comment by arielnh56** [comment]
I see where you are going with this and I like the idea.  I think I'd prefer to implement it with the read code in acePins() and the alternate setup triggered by a different constructor. 

thanks for the idea!

**Comment by arielnh56** [comment]
take a look at

https://github.com/arielnh56/ACE128/tree/directpins

added an example for new functions. I was rather miffed I could get the 8 pin variables to pass as an array to the constructor.

note that the pin numbering on the ACE128 is anticlockwise when viewed from above - I'd forgotten that, and it had me scratching my head for a bit.

**Comment by Bukmop123** [comment]
Hello Alastair, 
I have seen and tested your code right now. It looks good I am happy with the result. I need the sensor for a project and used your code to start. Thanks for that :)

Best regards
Bukmop

**Comment by Bukmop123** [comment]
By the way. In the header file you have 
`// ensure this library description is only included once
#ifndef ACE28_h
#define ACE128_h`
I suppose the 28 should be a 128.

Greetings
Bukmop

**Comment by arielnh56** [comment]
thanks for that - I will fix that. Well spotted!

**Pull request closed without merging**
